// frontend/blockchain/contractAddress.js
// AUTO-GENERATED by blockchain/scripts/deploy.js
// Do not edit manually — run npm run deploy:hardhat-local to update
// Last updated: 2026-10-03T09:52:30.235Z

export const CONTRACT_ADDRESSES = {
  31337: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  11155111: "0x0000000000000000000000000000000000000000",
};

export const SUPPORTED_CHAIN_IDS = [31337, 11155111];

export const getContractAddress = (chainId) => {
  const addr = CONTRACT_ADDRESSES[chainId];
  if (!addr || addr === "0x0000000000000000000000000000000000000000") {
    throw new Error(`No contract deployed on chain ${chainId}`);
  }
  return addr;
};
