// blockchain/scripts/address-config.js
// Contract address configuration for different networks
// This file helps generate the frontend contractAddress.js
//
// The actual network detection happens in the frontend via:
//   const { chainId } = await provider.getNetwork()
//   CONTRACT_ADDRESSES[chainId]

// Network chain IDs
const CHAIN_IDS = {
  HARDHAT_LOCAL: 31337,
  SEPOLIA: 11155111,
  // MAINNET: 1  (post-MVP)
};

// Template for frontend/blockchain/contractAddress.js
// Generated by deploy.js — do not edit manually
const FRONTEND_ADDRESS_TEMPLATE = (network, address) => `// frontend/blockchain/contractAddress.js
// AUTO-GENERATED by blockchain/scripts/deploy.js
// Do not edit manually — run npm run deploy:${network} to update
// Last updated: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  ${CHAIN_IDS.HARDHAT_LOCAL}: "${network === "hardhat-local" ? address : "0x0000000000000000000000000000000000000000"}",
  ${CHAIN_IDS.SEPOLIA}: "${network === "sepolia" ? address : "0x0000000000000000000000000000000000000000"}",
};

export const SUPPORTED_CHAIN_IDS = [${CHAIN_IDS.HARDHAT_LOCAL}, ${CHAIN_IDS.SEPOLIA}];

export const getContractAddress = (chainId) => {
  const addr = CONTRACT_ADDRESSES[chainId];
  if (!addr || addr === "0x0000000000000000000000000000000000000000") {
    throw new Error(\`No contract deployed on chain \${chainId}\`);
  }
  return addr;
};
`;

module.exports = {
  CHAIN_IDS,
  FRONTEND_ADDRESS_TEMPLATE,
};
